#!/bin/zsh
alias cmd1="source ~/.zshrc"
alias cmd2="mysql.server start"
alias cmd3="source /Users/lzhao/Documents/my_git/fsc/fsc_venv/bin/activate"
alias cmd4="cd /Users/lzhao/Documents/my_git/fsc/stocks"
alias cmd5="scrapy crawl nasdaq"
cmd1 && cmd2 && cmd3 && cmd4 && cmd5
