"""empty message

Revision ID: 1a4e89b82429
Revises: 83d489f4c957
Create Date: 2016-05-23 15:32:05.832797

"""

# revision identifiers, used by Alembic.
revision = '1a4e89b82429'
down_revision = '83d489f4c957'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('updatetime', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'updatetime')
    ### end Alembic commands ###
