"""empty message

Revision ID: 3853955a6226
Revises: a3b08070a47f
Create Date: 2016-05-15 22:03:55.344362

"""

# revision identifiers, used by Alembic.
revision = '3853955a6226'
down_revision = 'a3b08070a47f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('currentprice', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'currentprice')
    ### end Alembic commands ###
