"""add sharevolume column

Revision ID: 83d489f4c957
Revises: 3853955a6226
Create Date: 2016-05-20 18:40:38.567391

"""

# revision identifiers, used by Alembic.
revision = '83d489f4c957'
down_revision = '3853955a6226'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('sharevolume', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'sharevolume')
    ### end Alembic commands ###
